- name: WandbCallback
  configs:
    project: explainable-medical-coding
    entity: null
- name: SaveBestModelCallback
  configs:
    split: validation
    target: all
    metric: f1_macro
- name: EarlyStoppingCallback
  configs:
    split: validation
    target: all
    metric: f1_macro
    patience: 6
